-- MySQL Script generated by MySQL Workbench
-- 11/19/15 14:27:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Data for table `lang`
-- -----------------------------------------------------
START TRANSACTION;
USE `40496_dold_pim`;
INSERT INTO `lang` (`id`, `name`, `iso`, `sort`, `is_active`) VALUES (1, 'de', 'de', 1, 1);
INSERT INTO `lang` (`id`, `name`, `iso`, `sort`, `is_active`) VALUES (2, 'en', 'en', 2, 1);
INSERT INTO `lang` (`id`, `name`, `iso`, `sort`, `is_active`) VALUES (3, 'fr', 'fr', 3, 1);
INSERT INTO `lang` (`id`, `name`, `iso`, `sort`, `is_active`) VALUES (4, 'sp', 'es', 4, 1);
INSERT INTO `lang` (`id`, `name`, `iso`, `sort`, `is_active`) VALUES (5, 'po', 'po', 5, 1);
INSERT INTO `lang` (`id`, `name`, `iso`, `sort`, `is_active`) VALUES (6, 'ru', 'ru', 6, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
USE `40496_dold_pim`;
INSERT INTO `user` (`id`, `name`, `password`, `email`, `last_login`, `failes_login_count`, `is_locked`, `allow_products`, `allow_attributes`, `allow_templates`, `allow_admin`, `allow_delete`, `allow_edit`) VALUES (1, 'sysadmin', 'sysadmin', 'sysadmin@4fb.de', NULL, 0, 0, 1, 1, 1, 1, 1, 1);
INSERT INTO `user` (`id`, `name`, `password`, `email`, `last_login`, `failes_login_count`, `is_locked`, `allow_products`, `allow_attributes`, `allow_templates`, `allow_admin`, `allow_delete`, `allow_edit`) VALUES (2, 'Erdal Mersinlioglu', 'sysadmin', 'erdal.mersinlioglu@4fb.de', NULL, 0, 0, 1, 1, 1, 1, 1, 1);
INSERT INTO `user` (`id`, `name`, `password`, `email`, `last_login`, `failes_login_count`, `is_locked`, `allow_products`, `allow_attributes`, `allow_templates`, `allow_admin`, `allow_delete`, `allow_edit`) VALUES (3, 'Tester1', 'sysadmin', 'tester1@4fb.de', NULL, 0, 0, 1, 1, 1, 1, 1, 1);

COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
